### ISSUE TITLE
audioPlot Step 3.2 

### ISSUE THREAD

**Issue by Lucius-lsr** [saturn-lab/audioPlot#6]
使用修改后的py文件后，产生新的错误

Original error was: dlopen(/anaconda3/lib/python3.7/sitepackages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /anaconda3/lib/python3.7/sitepackages/numpy/core/_multiarray_umath.cpython-37m-darwin.so
  Reason: image not found

**Comment by HaoyunHong** [comment]
这不是新代码的原因。我没有使用anaconda，win10+newest pip + python 3.7.4出图一切正常。看错误的提示信息应该是你的anaconda里面有一个库没有装，或者因为某些原因它就消失了，stackoverflow上有https://stackoverflow.com/questions/48934912/anaconda-numpy-importerror-osx 类似的问题，然后回答是“I would strongly recommend you to reinstall anaconda3 ”，我觉得大概有道理:joy:，但是嘞，其实也可以不用anacoda，直接全部用pip:smirk:
或者可以再在anaconda上重装一下错误信息里提到的numpy包。
